---
- name: "Provision blackboard-binder server"
  hosts: localhost
  become: yes
  tasks:
  - name: "Install apps using apt-get"
    apt: name={{item}} state=present
    with_items:
      - libxml2
      - libxml2-dev
      - libxslt1-dev
      - python-dev
      - chromium-browser
    - name: "Get Chrome WebDriver for selenium"
      unarchive: 
        src=https://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
        dest=/usr/bin/ 
    - name: "Set execute permission on chromedriver"
      chmod: path=/usr/bin/chromedriver state=file mode=u+x

    - name: "Install python packages"
      pip: requirements=requirements.txt virtualenv=env
     

